require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'lib/ba/ba_commands/usage_stats_command.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/ba/ba_commands/usage_stats_command.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/ba/ba_commands/usage_stats_command.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/ba/ba_support/reaction_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/ba/ba_support/reaction_spec.rb'
