# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'discordrb'
gem 'pg'
gem 'rake'

group :test do
  gem 'pry-byebug'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
end
