name: Bot Build

on: [push, pull_request]

jobs:
  build:
    env:
      TOKEN: 'completely real token'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Lint
      run: |
        bundle exec rubocop
    - name: Test Bot
      run: |
        bundle exec rspec
